$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    autoplay:1000,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:5
        },
        2000:{
            items:5
        }
    }
})
